package controller;

import data.Location;
import data.TaxiQuery;

import schema.TransportType;
import service.Service;

import org.junit.Assert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

/**
 * This is a handful of unit tests to verify that the API layer is correctly responding to success and failure
 * conditions that can be generated by the business layer.
 *
 * Ideas for future tests are to expand on these kinds of unit tests and also to add system/integration tests.
 * The system/integration tests would make use of a test DB with known data sets. In this kind of
 * environment, we would run the REST service live (against the test DB), execute API calls against it (passing
 * in all sorts of valid or invalid data), and verify that the APIs in question respond properly.
 */
@RunWith(MockitoJUnitRunner.class)
class TestNyTripData {
    @Mock private Service mockService;
    @InjectMocks private NyTripData nyTripData;

    private final String ERROR_MSG = "Test code: Unable to access the REST service.";
    private final String ZERO_LENGTH_STR = "";

    @BeforeEach
    void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testGetLocationsSuccess() throws Exception {
        List<Location> list = new ArrayList<>();

        list.add(new Location(1, "EWR", "Newark Airport"));
        list.add(new Location(2, "Queens", "Jamaica Bay"));

        when(mockService.getLocations(ZERO_LENGTH_STR)).thenReturn(list);

        ResponseEntity<String> responseEntity = nyTripData.getLocations(ZERO_LENGTH_STR);

        verify(mockService, times(1)).getLocations(ZERO_LENGTH_STR);

        Assert.assertEquals(responseEntity.getStatusCode(), HttpStatus.OK);
    }

    @Test
    void testGetLocationsFailure() throws Exception {
        int fromLocationId = 100;
        int toLocationId = 200;
        TransportType transportType = TransportType.NONE;

        Exception exception = new Exception(ERROR_MSG);

        doThrow(exception).when(mockService).getTaxiQuery(fromLocationId, toLocationId, transportType);

        ResponseEntity<String> responseEntity = nyTripData.getTaxiQuery(fromLocationId, toLocationId, ZERO_LENGTH_STR);

        verify(mockService, times(1)).getTaxiQuery(fromLocationId, toLocationId, transportType);

        Assert.assertEquals(responseEntity.getStatusCode(), HttpStatus.INTERNAL_SERVER_ERROR);
        Assert.assertEquals(responseEntity.getBody(), "{\"error\": \"" + ERROR_MSG + "\"}");
    }

    @Test
    void testTaxiQuerySuccess() throws Exception {
        int fromLocationId = 100;
        int toLocationId = 200;
        TransportType transportType = TransportType.NONE;

        TaxiQuery query = new TaxiQuery(300, 10.50f);
        Optional<TaxiQuery> opt = Optional.of(query);

        when(mockService.getTaxiQuery(fromLocationId, toLocationId, transportType)).thenReturn(opt);

        ResponseEntity<String> responseEntity = nyTripData.getTaxiQuery(fromLocationId, toLocationId, ZERO_LENGTH_STR);

        verify(mockService, times(1)).getTaxiQuery(fromLocationId, toLocationId, transportType);

        Assert.assertEquals(responseEntity.getStatusCode(), HttpStatus.OK);
    }

    @Test
    void testTaxiQueryFailure() throws Exception {
        Exception exception = new Exception(ERROR_MSG);

        doThrow(exception).when(mockService).getLocations(ZERO_LENGTH_STR);

        ResponseEntity<String> responseEntity = nyTripData.getLocations(ZERO_LENGTH_STR);

        verify(mockService, times(1)).getLocations(ZERO_LENGTH_STR);

        Assert.assertEquals(responseEntity.getStatusCode(), HttpStatus.INTERNAL_SERVER_ERROR);
        Assert.assertEquals(responseEntity.getBody(), "{\"error\": \"" + ERROR_MSG + "\"}");
    }
}
