CREATE TABLE LOCATION (
    ID              INT,
    BOROUGH         VARCHAR(75),
    ZONE            VARCHAR(75),
    PRIMARY KEY("ID")
);

CREATE TABLE TRIP (
	ID              INT,
	PICK_UP_TIME    TIMESTAMP,
	DROP_OFF_TIME   TIMESTAMP,
	PICK_UP_LOC_ID  INT   DEFAULT 0,
	DROP_OFF_LOC_ID INT   DEFAULT 0,
	COST            REAL  DEFAULT 0,
	TRANSPORT_TYPE  INT   NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(PICK_UP_LOC_ID) REFERENCES LOCATION(ID),
	FOREIGN KEY(DROP_OFF_LOC_ID) REFERENCES LOCATION(ID)
);
