CREATE TABLE LOCATION (
    ID              INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    BOROUGH         VARCHAR(75),
    ZONE            VARCHAR(75),
    PRIMARY KEY("ID")
);

CREATE TABLE TRIP (
	ID              INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	PICK_UP_TIME    TIMESTAMP NOT NULL,
	DROP_OFF_TIME   TIMESTAMP NOT NULL,
	PICK_UP_LOC_ID  INT   DEFAULT 265, /* 265 is associated with an unknown location in the DB */
	DROP_OFF_LOC_ID INT   DEFAULT 265, /* 265 is associated with an unknown location in the DB */
	COST            REAL  DEFAULT 0,
	TRANSPORT_TYPE  INT   NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(PICK_UP_LOC_ID) REFERENCES LOCATION(ID),
	FOREIGN KEY(DROP_OFF_LOC_ID) REFERENCES LOCATION(ID)
);
